image: ghdl/ext:vunit
before_script:
    - apt-get -y install lcov make

build_ip_and_tests:
    stage: build
    allow_failure: true
    script:
        - cd test
        - make elaborate

.build_driver:
    stage: build
    allow_failure: true
    script:
        - cd driver
        - "make -j`nproc`"

test_ip:
    stage: test
    allow_failure: true
    script:
        - cd test
        - make test XUNIT=1
        - make coverage
    coverage: "/lines......: ([^%]+%)/"
    artifacts:
        paths:
            - code_html
            - test.xml
