image: mjerabek/ghdl:upstream-gcc
before_script:
    - "export PATH=/opt/ghdl/bin:$PATH"
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - export PYTHONUNBUFFERED=1

build_ip_and_tests:
    stage: build
    artifacts:
        paths: &vunit_build_paths
            - test/build
        expire_in: 1 hour
    script:
        - cd test
        - make elaborate
    only: &only
        - master     # Run on all changes to master branch
        - tags       # Run on all tags
        - triggers   # Run by trigger (on merge request)
        - web        # Run by manual request from web UI

.build_driver:
    stage: build
    allow_failure: true
    only: *only
    script:
        - cd driver
        - "make -j`nproc`"

test_ip_fast:
    stage: test
    only: *only
    dependencies: [build_ip_and_tests]
    script:
        - cd test
        - make test_fast
        - make coverage
    coverage: "/lines......: ([^%]+%)/"
    artifacts:
        when: always
        paths:
            - test/code_html
            - test/tests_fast.xml
            - test/xunit.xsl

test_ip_nightly:
    stage: test
    dependencies: [build_ip_and_tests]
    only:
        - schedules
    script:
        - cd test
        - make test_nightly
    artifacts:
        when: always
        paths:
            - test/tests_nightly.xml
            - test/xunit.xsl

pages:
    stage: deploy
    when: always
    #dependencies: [test_ip_unit, test_ip_sanity]
    script:
        - mkdir -p public
        - cp test/xunit.xsl public/
        - cp test/tests_*.xml public/
        - mv test/code_html public/coverage || true
    only:
        - master
    artifacts:
        paths:
            - public
