image: registry.gitlab.com/canfd/server-tools/ghdl
before_script:
    - "export PATH=/opt/ghdl/bin:$PATH"
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - export PYTHONUNBUFFERED=1

stages:
    - precheck
    - build
    - test
    - deploy

check_component:
    stage: precheck
    script:
        - mv src/component.xml src/component.xml-orig
        - scripts/gen_vivado_component.py
        - diff -u src/component.xml-orig src/component.xml || (echo "Vivado component file is not up-to-date. Either run scripts/gen_vivado_component.py or download the file from this job's artifacts."; exit 1)
    artifacts:
        expire_in: 1 week
        paths:
            - src/component.xml

build_ip_and_tests:
    stage: build
    artifacts:
        paths: &vunit_build_paths
            - test/build
        expire_in: 1 hour
    script:
        - cd test
        - make elaborate
        # Do not include the huge binaries in artifacts.
        - rm -R build/vunit_out/test_output
    only: &only
        - master     # Run on all changes to master branch
        - tags       # Run on all tags
        - triggers   # Run by trigger (on merge request)
        - web        # Run by manual request from web UI

build_driver:
    stage: build
    only: *only
    script:
        - cd driver
        - "make -j`nproc`"

build_doc:
    stage: build
    tags: [virt]  # runner in virtual, without docker, with new lyx
    only:
        - master
        - tags
        - web # debug only!
    #image: hathi.duckdns.org/user/lyx:buster
    script:
        - export LC_ALL=en_US.UTF-8
        - export LANG=en_US.UTF-8
        - export TMPDIR=/var/tmp # not enouhg room in tmpfs
        - make -C doc/core
    artifacts:
        paths:
            - doc/core/Progdokum.pdf

build_linux_driver:
    stage: build
    only: *only
    image: registry.gitlab.com/canfd/server-tools/ctucanfd_drvtest
    script:
        - cd driver/linux
        - "make -j`nproc` KDIR=/linux/build"
    artifacts:
        paths:
            - driver/linux/ctucanfd.ko

test_ip_fast:
    stage: test
    only: *only
    dependencies: [build_ip_and_tests]
    script:
        - cd test
        - make test_fast
        - make coverage
        - make functional_coverage
    coverage: "/lines......: ([^%]+%)/"
    artifacts:
        when: always
        paths:
            - test/code_html
            - test/tests_fast.xml
            - test/xunit.xsl
            - test/build/functional_coverage
        reports:
            junit: [test/tests_fast.xml]

test_ip_nightly:
    stage: test
    dependencies: [build_ip_and_tests]
    only:
        - schedules
    script:
        - cd test
        - make test_nightly
    artifacts:
        when: always
        paths:
            - test/tests_nightly.xml
            - test/xunit.xsl
        reports:
            junit: [test/tests_nightly.xml]

pages:
    stage: deploy
    when: always
    #dependencies: [test_ip_unit, test_ip_sanity]
    script:
        - mkdir -p public
        - cp test/xunit.xsl public/
        - cp test/tests_*.xml public/
        - mv test/code_html public/coverage || true
        - cp doc/core/Progdokum.pdf public/ || true
        - mkdir public/functional_coverage
        - cp -R test/build/functional_coverage/* public/functional_coverage || true
    only:
        - master
    artifacts:
        paths:
            - public
