image: mjerabek/ghdl
before_script:
    - "export PATH=/opt/ghdl/bin:$PATH"

build_ip_and_tests:
    stage: build
    artifacts:
        paths: &vunit_build_paths
            - test/vunit_out
            - 'test/*.gcda'
            - 'test/*.gcno'
        expire_in: 1 hour
    script:
        - cd test
        - make elaborate
    only: &only
        - master     # Run on all changes to master branch
        - tags       # Run on all tags
        - schedules  # Run on schedule
        - triggers   # Run by trigger (on merge request)
        - web        # Run by manual request from web UI

.build_driver:
    stage: build
    allow_failure: true
    only: *only
    script:
        - cd driver
        - "make -j`nproc`"

test_ip_unit:
    stage: test
    only: *only
    dependencies: [build_ip_and_tests]
    artifacts:
        paths: *vunit_build_paths
    script:
        - cd test
        - make test_unit XUNIT=1
        - make coverage
    coverage: "/lines......: ([^%]+%)/"
    artifacts:
        paths:
            - test/code_html
            - test/test_unit.xml
            - test/xunit.xsl

test_ip_sanity:
    stage: test
    dependencies: [build_ip_and_tests]
    artifacts:
        paths: *vunit_build_paths
    only:
        - schedules
    script:
        - cd test
        - make test_sanity XUNIT=1
    artifacts:
        paths:
            - test/test_sanity.xml
            - test/xunit.xsl

pages:
    stage: deploy
    when: always
    #dependencies: [test_ip_unit, test_ip_sanity]
    allow_failure: true # for debugging
    script:
        - mkdir -p public
        - cp xunit.xsl public/
        - cp test_*.xml public/
        - mv code_html public/coverage || true
    only:
        - master
    artifacts:
        paths:
            - public
