image: mjerabek/ghdl
before_script:
    - "export PATH=/opt/ghdl/bin:$PATH"

build_ip_and_tests:
    stage: build
    cache: &vunit_cache
        paths:
            - test/vunit_out
            - 'test/*.gcda'
            - 'test/*.gcno'
    script:
        - cd test
        - make elaborate

.build_driver:
    stage: build
    allow_failure: true
    script:
        - cd driver
        - "make -j`nproc`"

test_ip_unit:
    stage: test
    cache: *vunit_cache
    script:
        - cd test
        - make test_unit XUNIT=1
        - make coverage
    coverage: "/lines......: ([^%]+%)/"
    artifacts:
        paths:
            - test/code_html
            - test/test_unit.xml
