image: mjerabek/ghdl
before_script:
    - "export PATH=/opt/ghdl/bin:$PATH"

build_ip_and_tests:
    stage: build
    cache:
        policy: push
        paths: &vunit_cache_paths
            - test/vunit_out
            - 'test/*.gcda'
            - 'test/*.gcno'
    script:
        - cd test
        - make elaborate
    only: &only
        - master     # Run on all changes to master branch
        - tags       # Run on all tags
        - schedules  # Run on schedule
        - triggers   # Run by trigger (on merge request)
        - web        # Run by manual request from web UI

.build_driver:
    stage: build
    allow_failure: true
    only: *only
    script:
        - cd driver
        - "make -j`nproc`"

test_ip_unit:
    stage: test
    only: *only
    cache:
        policy: pull
        paths: *vunit_cache_paths
    script:
        - cd test
        - make test_unit XUNIT=1
        - make coverage
    coverage: "/lines......: ([^%]+%)/"
    artifacts:
        paths:
            - test/code_html
            - test/test_unit.xml

test_ip_sanity:
    stage: test
    cache:
        policy: pull
        paths: *vunit_cache_paths
    only:
        - schedules
    script:
        - cd test
        - make test_sanity XUNIT=1
    artifacts:
        paths:
            - test/test_unit.xml
